config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
    # get '/tasks', to: "tasks#index" # get all your tasks.
    # get '/tasks/:id' to: "tasks#show"#get a precise task, e.g GET '/tasks/3' fetches the task with id=3
    # get '/tasks/new' to: "tasks#new" #get the form to create a new task
    # post '/tasks' to: "tasks#create"# post a new task
    # get '/tasks/:id/edit' to: "tasks#edit" # get the form to edit an existing task
    # patch '/tasks/:id' to: "tasks#update" # update an existing task
    # delete '/tasks/:id' to: "tasks#destroy"# delete an existing task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


    def index
      @tasks = Task.all

    end

    def show
      @task = Task.find(params[:id])
    end

    def new
      @task = Task.new

    end

    def create
      @task = Task.new(task_params)
      @task.save
      redirect_to task_path(@task)
    end

    def edit
      @task = Task.find(params[:id])
    end

    def update
      @task = Task.find(params[:id])
      @task.update(task_params)
      redirect_to task_path(@task)
    end

    def destroy
      @task = Task.find(params[:id])
      @task.destroy
      redirect_to tasks_path
    end

    private

    def task_params
      params.require(:task).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>See below the list of your opened tasks</h1>

<%= render 'form' %>

<%= link_to "Home", tasks_path %>

app/views/tasks/index.html.erb
<h1>Welcome to the best Task Manager<h1>

<% @tasks.each do |task| %>
  <h2><%= task.name %></h2>
  <%= link_to "Show tasks", task_path(task) %>
  <%= link_to "Edit tasks", edit_task_path(task) %>
  <%= link_to "Delete tasks", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure"} %>
<% end %>

app/views/tasks/new.html.erb
<h1>Create a new task and indicate its priority</h1>

<%= render 'form' %>

<%= link_to "Home", tasks_path %>

app/views/tasks/show.html.erb
<h1>This is my show page</h1>

<h2><%= @task.name %></h2>
<%= link_to "Home", tasks_path %>